// const ROOT_DIR = "assets/";
// const DUCKYSCRIPT_CODE_DIR = "code/";
// const FULL_PATH = ROOT_DIR+DUCKYSCRIPT_CODE_DIR;
// const COOKBOOK_EXTENSION_FILE = ".txt";


// export const PATH_TO_COOKBOOK = {
// 	PAYLOAD_INTRO_3_0 : FULL_PATH + "3_0_PAYLOAD_INTRO" + COOKBOOK_EXTENSION_FILE,
// 	DETECT_READY_3_0 : FULL_PATH + "3_0_DETECT_READY" + COOKBOOK_EXTENSION_FILE,
// 	PASSIVE_WINDOWS_DETECT_3_0 : FULL_PATH + "3_0_PASSIVE_WINDOWS_DETECT" + COOKBOOK_EXTENSION_FILE,
// 	ERASE_TRACES_POWERSHELL_3_0 : FULL_PATH + "3_0_ERASE_TRACES_POWERSHELL" + COOKBOOK_EXTENSION_FILE,
// 	ERASE_TRACES_SHELL_3_0 : FULL_PATH + "3_0_ERASE_TRACES_SHELL" + COOKBOOK_EXTENSION_FILE,
// 	EXFILTRATE_FILES_USING_DROPBOX_WINDOWS_3_0 : FULL_PATH + "3_0_EXFILTRATE_FILES_USING_DROPBOX_WINDOWS" + COOKBOOK_EXTENSION_FILE,
// 	OPEN_POWERSHELL_3_0 : FULL_PATH + "3_0_OPEN_POWERSHELL" + COOKBOOK_EXTENSION_FILE,
// 	SAVE_FILES_IN_RUBBER_DUCKY_STORAGE_WINDOWS_3_0 : FULL_PATH + "3_0_SAVE_FILES_IN_RUBBER_DUCKY_STORAGE_WINDOWS" + COOKBOOK_EXTENSION_FILE,
// 	GENERALIZED_WINDOWS_USER_PATH_3_0 : FULL_PATH + "3_0_GENERALIZED_WINDOWS_USER_PATH" + COOKBOOK_EXTENSION_FILE,
// 	PHYSICAL_EXFILTRATION_3_0 : FULL_PATH + "3_0_PHYSICAL_EXFILTRATION" + COOKBOOK_EXTENSION_FILE,
// 	NETWORK_EXFILTRATION_3_0 : FULL_PATH + "3_0_NETWORK_EXFILTRATION" + COOKBOOK_EXTENSION_FILE,
// 	PAYLOAD_INTRO_1_0 : FULL_PATH + "1_0_PAYLOAD_INTRO" + COOKBOOK_EXTENSION_FILE,
// 	ERASE_TRACES_POWERSHELL_1_0 : FULL_PATH + "1_0_ERASE_TRACES_POWERSHELL" + COOKBOOK_EXTENSION_FILE,
// 	ERASE_TRACES_SHELL_1_0 : FULL_PATH + "1_0_ERASE_TRACES_SHELL" + COOKBOOK_EXTENSION_FILE,
// 	EXFILTRATE_FILES_USING_DROPBOX_WINDOWS_1_0 : FULL_PATH + "1_0_EXFILTRATE_FILES_USING_DROPBOX_WINDOWS" + COOKBOOK_EXTENSION_FILE,
// 	OPEN_POWERSHELL_1_0 : FULL_PATH + "1_0_OPEN_POWERSHELL" + COOKBOOK_EXTENSION_FILE,
// 	GENERALIZED_WINDOWS_USER_PATH_1_0 : FULL_PATH + "1_0_GENERALIZED_WINDOWS_USER_PATH" + COOKBOOK_EXTENSION_FILE,
// 	OPEN_SHELL : FULL_PATH + "OPEN_SHELL" + COOKBOOK_EXTENSION_FILE
// };


const ROOT_DIR = "assets/";
const DUCKYSCRIPT_CODE_DIR = "code/";
const FULL_PATH = ROOT_DIR + DUCKYSCRIPT_CODE_DIR;
const COOKBOOK_EXTENSION_FILE = ".txt";

// Funzione di utilità per comporre il path
const createPath = (filename: string) => `${FULL_PATH}${filename}${COOKBOOK_EXTENSION_FILE}`;

export const PATH_TO_COOKBOOK = {
  PAYLOAD_INTRO_3_0: createPath("3_0_PAYLOAD_INTRO"),
  DETECT_READY_3_0: createPath("3_0_DETECT_READY"),
  PASSIVE_WINDOWS_DETECT_3_0: createPath("3_0_PASSIVE_WINDOWS_DETECT"),
  ERASE_TRACES_POWERSHELL_3_0: createPath("3_0_ERASE_TRACES_POWERSHELL"),
  ERASE_TRACES_SHELL_3_0: createPath("3_0_ERASE_TRACES_SHELL"),
  EXFILTRATE_FILES_USING_DROPBOX_WINDOWS_3_0: createPath("3_0_EXFILTRATE_FILES_USING_DROPBOX_WINDOWS"),
  OPEN_POWERSHELL_3_0: createPath("3_0_OPEN_POWERSHELL"),
  SAVE_FILES_IN_RUBBER_DUCKY_STORAGE_WINDOWS_3_0: createPath("3_0_SAVE_FILES_IN_RUBBER_DUCKY_STORAGE_WINDOWS"),
  GENERALIZED_WINDOWS_USER_PATH_3_0: createPath("3_0_GENERALIZED_WINDOWS_USER_PATH"),
  PHYSICAL_EXFILTRATION_3_0: createPath("3_0_PHYSICAL_EXFILTRATION"),
  NETWORK_EXFILTRATION_3_0: createPath("3_0_NETWORK_EXFILTRATION"),

  PAYLOAD_INTRO_1_0: createPath("1_0_PAYLOAD_INTRO"),
  ERASE_TRACES_POWERSHELL_1_0: createPath("1_0_ERASE_TRACES_POWERSHELL"),
  ERASE_TRACES_SHELL_1_0: createPath("1_0_ERASE_TRACES_SHELL"),
  EXFILTRATE_FILES_USING_DROPBOX_WINDOWS_1_0: createPath("1_0_EXFILTRATE_FILES_USING_DROPBOX_WINDOWS"),
  OPEN_POWERSHELL_1_0: createPath("1_0_OPEN_POWERSHELL"),
  GENERALIZED_WINDOWS_USER_PATH_1_0: createPath("1_0_GENERALIZED_WINDOWS_USER_PATH"),

  OPEN_SHELL: createPath("OPEN_SHELL"),
};
